version: "3.9"

services:
  # === PostgreSQL Database ===
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smart_inventory
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../backend:/docker-entrypoint-initdb.d/backend:ro
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    ports:
      - "5432:5432"
    networks:
      - backend

  # === Inventory Service ===
  inventory-service:
    build:
      context: ../
      dockerfile: infra/docker/Dockerfile.inventory-service
    container_name: inventory_service
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/smart_inventory
      SERVICE_PORT: 4001
    depends_on:
      - postgres
    networks:
      - backend

  # === Order Service ===
  order-service:
    build:
      context: ../
      dockerfile: infra/docker/Dockerfile.order-service
    container_name: order_service_1
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/smart_inventory
      SERVICE_PORT: 4002
    depends_on:
      - postgres
      - inventory-service
    networks:
      - backend

  # === API Gateway ===
  api-gateway:
    build:
      context: ../
      dockerfile: infra/docker/Dockerfile.api-gateway
    container_name: api_gateway
    restart: always
    ports:
      - "4000:4000"
    environment:
      ORDER_SERVICE_URL: http://order_backend
      INVENTORY_SERVICE_URL: http://inventory_backend
    depends_on:
      - order-service
      - inventory-service
    networks:
      - backend

  # === Nginx Load Balancer ===
  nginx:
    image: nginx:latest
    container_name: nginx_gateway
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-gateway
      - inventory-service
      - order-service
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  pgdata:
